<a href="https://colab.research.google.com/github/Meisam-sh/Machine_Learning_Python_With_Meisam_Shabanpoor/blob/main/Pytorch_Basic_statement_toturial_with%20tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import numpy as np

In [3]:
data=[[1,2],[3,5]]

In [4]:
#convert data to tensor
tensor_data=torch.tensor(data)

In [5]:
#it has a structure a lilte like numpy#
tensor_data

tensor([[1, 2],
        [3, 5]])

In [6]:
# Make Zero array by torch.zeros based on shape variable
shape=(5,4)
torch.zeros(shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
# make an array based on shpae with torch.rand
tensor_rand=torch.rand(shape)
tensor_rand

tensor([[0.7652, 0.7463, 0.1751, 0.3495],
        [0.3007, 0.0971, 0.5991, 0.3451],
        [0.2041, 0.1948, 0.4833, 0.7796],
        [0.2581, 0.0627, 0.2907, 0.4017],
        [0.5234, 0.5943, 0.3536, 0.8036]])

In [8]:
#consider to the range that every function causes.
tensor_randn=torch.randn(shape)
tensor_randn

tensor([[-1.1145,  1.5364,  0.6046, -0.1255],
        [-1.4859,  0.8296, -0.0585,  0.5709],
        [ 0.4175,  0.7228,  0.9797, -1.8710],
        [ 0.9842, -0.4694, -0.7293,  0.5308],
        [-1.2002, -1.4262,  0.5498, -1.4780]])

In [9]:
print(f'tensor_randn type is: {tensor_randn.dtype}')
print(f'tensor_rand type is : {tensor_rand.dtype}')
print(f'tensor_data type is : {tensor_data.dtype}')

tensor_randn type is: torch.float32
tensor_rand type is : torch.float32
tensor_data type is : torch.int64


In [10]:
tensor_rand.shape

torch.Size([5, 4])

In [11]:
tensor_data.device

device(type='cpu')

In [38]:
tensor_data=tensor_data.to("cuda")

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

In [12]:
# Before this script I change the setting of Ram on Google Colab and then :
tensor_data=tensor_data.to("cuda")

In [13]:
tensor_data.device

device(type='cuda', index=0)

In [11]:
tensor_one=torch.ones(shape)

In [12]:
tensor_one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
tensor_rand[0]

tensor([0.7652, 0.7463, 0.1751, 0.3495])

In [14]:
tensor_one[3][3]

tensor(1.)

In [20]:
#tensor's Index starts with 0
tensor_randn[3,2]=19
tensor_randn

tensor([[-1.1145,  1.5364,  0.6046, -0.1255],
        [-1.4859,  0.8296, -0.0585,  0.5709],
        [ 0.4175,  0.7228,  0.9797, -1.8710],
        [ 0.9842, -0.4694, 19.0000,  0.5308],
        [-1.2002, -1.4262,  0.5498, -1.4780]])

In [22]:
tensor_one[...,1]=23
tensor_one[...,3]=19
tensor_one

tensor([[ 1., 23.,  1., 19.],
        [ 1., 23.,  1., 19.],
        [ 1., 23.,  1., 19.],
        [ 1., 23.,  1., 19.],
        [ 1., 23.,  1., 19.]])

In [24]:
#tenso.T means transpose of tensor
# @ is used insted of * for multiply 2 matrixes
T_tensor_one=tensor_one@tensor_one.T
T_tensor_one

tensor([[892., 892., 892., 892., 892.],
        [892., 892., 892., 892., 892.],
        [892., 892., 892., 892., 892.],
        [892., 892., 892., 892., 892.],
        [892., 892., 892., 892., 892.]])

In [27]:
#Item y item multiply of to matrixes with *
m_matrix=tensor_one*tensor_one
m_matrix

tensor([[  1., 529.,   1., 361.],
        [  1., 529.,   1., 361.],
        [  1., 529.,   1., 361.],
        [  1., 529.,   1., 361.],
        [  1., 529.,   1., 361.]])